### PR TITLE
Foundational Security: DynamoDB/DAX policies

### PR DESCRIPTION
**Pull request by disq**
Needs [the new resources](https://github.com/cloudquery/cq-provider-aws/pull/324)

### CODE REVIEW

**Review by bbernays — APPROVED** [review]
LGTM

**Review by spangenberg — APPROVED** [review]
LGTM

**Comment by disq** [comment]
This apparently needs `applicationautoscaling` resource to be 100%, otherwise there's no way of telling whether a non-global table (which doesn't have replicas) has auto-scaling turned on or not.

**Comment by disq** [comment]
Ready to merge since the [resource PR](https://github.com/cloudquery/cq-provider-aws/pull/324) is merged, but would need a new provider release.

**Pull request merged**
